Algoritmo "aula 7"
Var
 nome: caractere
 produtos: vetor [1..4] de caractere
 numeros: vetor [1..3] de inteiro
 i: inteiro

Inicio
 nome<- "victor"
 nome<-"alessandro"
 
 produtos[1]<- "Banana"
 produtos [2]<- "salgadinho"
 produtos [3]<- "Coca-Cola"
 produtos [4]<- "Café"


 para  i<- 1 ate 3 faca
 leia (numeros[i])
 
 
 fimpara
 
  para  i<- 1 ate 3 faca
escreval ("m", i,"°", numeros[i])


 fimpara




Fimalgoritmo