Algoritmo "aula6"

Var
i : inteiro
repete: caractere
 condicao: logico

Inicio
condicao <- verdadeiro
   enquanto  (condicao) faca


   escreval("Repete? S/N")
   leia(repete)

   se(repete = "S") entao
   condicao<- verdadeiro
   senao
    condicao<- falso
    fimse
    fimenquanto
    
//PROCEDIMENTO
PROCEDIMENTO TESTE()
var
data: caractere

inicio
data<- "19/02/2026"
 ESCREVAL ("FUNCIONOU!")

  escreval (data)

FIMPROCEDIMENTO
escreval(repete)

TESTE()
TESTE()





Fimalgoritmo